[package]
name = "gauge_logic"
version = "0.1.0"
authors = ["Tom Langwaldt <git@tomlangwaldt.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
msfs = { git = "https://github.com/flybywiresim/msfs-rs", branch = "main" }

[profile.release]
lto = true
strip = true